/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDocumentationFindNo);
  }
}(this, function(expect, OpenApiDocumentationFindNo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChatResponseDTO', function() {
    it('should create an instance of ChatResponseDTO', function() {
      // uncomment below and update the code to test ChatResponseDTO
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be.a(OpenApiDocumentationFindNo.ChatResponseDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property listingId (base name: "listingId")', function() {
      // uncomment below and update the code to test the property listingId
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property buyerFirstName (base name: "buyerFirstName")', function() {
      // uncomment below and update the code to test the property buyerFirstName
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property buyerLastName (base name: "buyerLastName")', function() {
      // uncomment below and update the code to test the property buyerLastName
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property sellerFirstName (base name: "sellerFirstName")', function() {
      // uncomment below and update the code to test the property sellerFirstName
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property sellerLastName (base name: "sellerLastName")', function() {
      // uncomment below and update the code to test the property sellerLastName
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property messages (base name: "messages")', function() {
      // uncomment below and update the code to test the property messages
      //var instance = new OpenApiDocumentationFindNo.ChatResponseDTO();
      //expect(instance).to.be();
    });

  });

}));
