/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient.js';
import AuthenticationRequestDTO from './model/AuthenticationRequestDTO.js';
import BookmarkRequestDTO from './model/BookmarkRequestDTO.js';
import BookmarkResponseDTO from './model/BookmarkResponseDTO.js';
import CategoryCreationRequestDTO from './model/CategoryCreationRequestDTO.js';
import CategoryListResponseDTO from './model/CategoryListResponseDTO.js';
import CategoryResponseDTO from './model/CategoryResponseDTO.js';
import ChatResponseDTO from './model/ChatResponseDTO.js';
import ListingCreationRequestDTO from './model/ListingCreationRequestDTO.js';
import ListingListResponseDTO from './model/ListingListResponseDTO.js';
import ListingResponseDTO from './model/ListingResponseDTO.js';
import MessageRequestDTO from './model/MessageRequestDTO.js';
import MessageResponsetDTO from './model/MessageResponsetDTO.js';
import SearchHistoryListResponseDTO from './model/SearchHistoryListResponseDTO.js';
import SearchHistoryRequestDTO from './model/SearchHistoryRequestDTO.js';
import SearchHistoryResponseDTO from './model/SearchHistoryResponseDTO.js';
import TokenResponseDTO from './model/TokenResponseDTO.js';
import UserRequestDTO from './model/UserRequestDTO.js';
import UserResponseDTO from './model/UserResponseDTO.js';
import AuthenticationControllerApi from './api/AuthenticationControllerApi.js';
import BookmarkControllerApi from './api/BookmarkControllerApi.js';
import CategoryControllerApi from './api/CategoryControllerApi.js';
import ChatControllerApi from './api/ChatControllerApi.js';
import ListingControllerApi from './api/ListingControllerApi.js';
import SearchHistoryControllerApi from './api/SearchHistoryControllerApi.js';
import UserControllerApi from './api/UserControllerApi.js';


/**
* OpenApi documentation for find.no.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDocumentationFindNo = require('index'); // See note below*.
* var xxxSvc = new OpenApiDocumentationFindNo.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDocumentationFindNo.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDocumentationFindNo.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDocumentationFindNo.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthenticationRequestDTO model constructor.
     * @property {module:model/AuthenticationRequestDTO}
     */
    AuthenticationRequestDTO,

    /**
     * The BookmarkRequestDTO model constructor.
     * @property {module:model/BookmarkRequestDTO}
     */
    BookmarkRequestDTO,

    /**
     * The BookmarkResponseDTO model constructor.
     * @property {module:model/BookmarkResponseDTO}
     */
    BookmarkResponseDTO,

    /**
     * The CategoryCreationRequestDTO model constructor.
     * @property {module:model/CategoryCreationRequestDTO}
     */
    CategoryCreationRequestDTO,

    /**
     * The CategoryListResponseDTO model constructor.
     * @property {module:model/CategoryListResponseDTO}
     */
    CategoryListResponseDTO,

    /**
     * The CategoryResponseDTO model constructor.
     * @property {module:model/CategoryResponseDTO}
     */
    CategoryResponseDTO,

    /**
     * The ChatResponseDTO model constructor.
     * @property {module:model/ChatResponseDTO}
     */
    ChatResponseDTO,

    /**
     * The ListingCreationRequestDTO model constructor.
     * @property {module:model/ListingCreationRequestDTO}
     */
    ListingCreationRequestDTO,

    /**
     * The ListingListResponseDTO model constructor.
     * @property {module:model/ListingListResponseDTO}
     */
    ListingListResponseDTO,

    /**
     * The ListingResponseDTO model constructor.
     * @property {module:model/ListingResponseDTO}
     */
    ListingResponseDTO,

    /**
     * The MessageRequestDTO model constructor.
     * @property {module:model/MessageRequestDTO}
     */
    MessageRequestDTO,

    /**
     * The MessageResponsetDTO model constructor.
     * @property {module:model/MessageResponsetDTO}
     */
    MessageResponsetDTO,

    /**
     * The SearchHistoryListResponseDTO model constructor.
     * @property {module:model/SearchHistoryListResponseDTO}
     */
    SearchHistoryListResponseDTO,

    /**
     * The SearchHistoryRequestDTO model constructor.
     * @property {module:model/SearchHistoryRequestDTO}
     */
    SearchHistoryRequestDTO,

    /**
     * The SearchHistoryResponseDTO model constructor.
     * @property {module:model/SearchHistoryResponseDTO}
     */
    SearchHistoryResponseDTO,

    /**
     * The TokenResponseDTO model constructor.
     * @property {module:model/TokenResponseDTO}
     */
    TokenResponseDTO,

    /**
     * The UserRequestDTO model constructor.
     * @property {module:model/UserRequestDTO}
     */
    UserRequestDTO,

    /**
     * The UserResponseDTO model constructor.
     * @property {module:model/UserResponseDTO}
     */
    UserResponseDTO,

    /**
    * The AuthenticationControllerApi service constructor.
    * @property {module:api/AuthenticationControllerApi}
    */
    AuthenticationControllerApi,

    /**
    * The BookmarkControllerApi service constructor.
    * @property {module:api/BookmarkControllerApi}
    */
    BookmarkControllerApi,

    /**
    * The CategoryControllerApi service constructor.
    * @property {module:api/CategoryControllerApi}
    */
    CategoryControllerApi,

    /**
    * The ChatControllerApi service constructor.
    * @property {module:api/ChatControllerApi}
    */
    ChatControllerApi,

    /**
    * The ListingControllerApi service constructor.
    * @property {module:api/ListingControllerApi}
    */
    ListingControllerApi,

    /**
    * The SearchHistoryControllerApi service constructor.
    * @property {module:api/SearchHistoryControllerApi}
    */
    SearchHistoryControllerApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi
};
