/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDocumentationFindNo);
  }
}(this, function(expect, OpenApiDocumentationFindNo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDocumentationFindNo.ChatControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChatControllerApi', function() {
    describe('addMessageToChat', function() {
      it('should call addMessageToChat successfully', function(done) {
        //uncomment below and update the code to test addMessageToChat
        //instance.addMessageToChat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createChatFromBuyer', function() {
      it('should call createChatFromBuyer successfully', function(done) {
        //uncomment below and update the code to test createChatFromBuyer
        //instance.createChatFromBuyer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllChatsForListing', function() {
      it('should call getAllChatsForListing successfully', function(done) {
        //uncomment below and update the code to test getAllChatsForListing
        //instance.getAllChatsForListing(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllChatsForUser', function() {
      it('should call getAllChatsForUser successfully', function(done) {
        //uncomment below and update the code to test getAllChatsForUser
        //instance.getAllChatsForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChat', function() {
      it('should call getChat successfully', function(done) {
        //uncomment below and update the code to test getChat
        //instance.getChat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
