services:
  backend:
    build: ./backend/SpringBackend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/SpringBackend/uploads:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 
    networks:
      - app-network

  frontend:
    build: ./frontend/VueFrontend
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
