/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BookmarkRequestDTO model module.
 * @module model/BookmarkRequestDTO
 * @version 1.0
 */
class BookmarkRequestDTO {
    /**
     * Constructs a new <code>BookmarkRequestDTO</code>.
     * @alias module:model/BookmarkRequestDTO
     */
    constructor() { 
        
        BookmarkRequestDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookmarkRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookmarkRequestDTO} obj Optional instance to populate.
     * @return {module:model/BookmarkRequestDTO} The populated <code>BookmarkRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookmarkRequestDTO();

            if (data.hasOwnProperty('listingId')) {
                obj['listingId'] = ApiClient.convertToType(data['listingId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookmarkRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookmarkRequestDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['listingId'] && !(typeof data['listingId'] === 'string' || data['listingId'] instanceof String)) {
            throw new Error("Expected the field `listingId` to be a primitive type in the JSON string but got " + data['listingId']);
        }

        return true;
    }


}



/**
 * @member {String} listingId
 */
BookmarkRequestDTO.prototype['listingId'] = undefined;






export default BookmarkRequestDTO;

