/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CategoryResponseDTO from './CategoryResponseDTO';

/**
 * The CategoryListResponseDTO model module.
 * @module model/CategoryListResponseDTO
 * @version 1.0
 */
class CategoryListResponseDTO {
    /**
     * Constructs a new <code>CategoryListResponseDTO</code>.
     * @alias module:model/CategoryListResponseDTO
     */
    constructor() { 
        
        CategoryListResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CategoryListResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryListResponseDTO} obj Optional instance to populate.
     * @return {module:model/CategoryListResponseDTO} The populated <code>CategoryListResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryListResponseDTO();

            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], [CategoryResponseDTO]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CategoryListResponseDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CategoryListResponseDTO</code>.
     */
    static validateJSON(data) {
        if (data['categories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['categories'])) {
                throw new Error("Expected the field `categories` to be an array in the JSON data but got " + data['categories']);
            }
            // validate the optional field `categories` (array)
            for (const item of data['categories']) {
                CategoryResponseDTO.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/CategoryResponseDTO>} categories
 */
CategoryListResponseDTO.prototype['categories'] = undefined;






export default CategoryListResponseDTO;

