/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The ListingCreationRequestDTO model module.
 * @module model/ListingCreationRequestDTO
 * @version 1.0
 */
class ListingCreationRequestDTO {
    /**
     * Constructs a new <code>ListingCreationRequestDTO</code>.
     * @alias module:model/ListingCreationRequestDTO
     */
    constructor() { 
        
        ListingCreationRequestDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListingCreationRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListingCreationRequestDTO} obj Optional instance to populate.
     * @return {module:model/ListingCreationRequestDTO} The populated <code>ListingCreationRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListingCreationRequestDTO();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('categoryName')) {
                obj['categoryName'] = ApiClient.convertToType(data['categoryName'], 'String');
            }
            if (data.hasOwnProperty('listingStatus')) {
                obj['listingStatus'] = ApiClient.convertToType(data['listingStatus'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListingCreationRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListingCreationRequestDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['categoryName'] && !(typeof data['categoryName'] === 'string' || data['categoryName'] instanceof String)) {
            throw new Error("Expected the field `categoryName` to be a primitive type in the JSON string but got " + data['categoryName']);
        }
        // ensure the json data is a string
        if (data['listingStatus'] && !(typeof data['listingStatus'] === 'string' || data['listingStatus'] instanceof String)) {
            throw new Error("Expected the field `listingStatus` to be a primitive type in the JSON string but got " + data['listingStatus']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
ListingCreationRequestDTO.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ListingCreationRequestDTO.prototype['description'] = undefined;

/**
 * @member {String} categoryName
 */
ListingCreationRequestDTO.prototype['categoryName'] = undefined;

/**
 * @member {String} listingStatus
 */
ListingCreationRequestDTO.prototype['listingStatus'] = undefined;

/**
 * @member {Number} price
 */
ListingCreationRequestDTO.prototype['price'] = undefined;

/**
 * @member {Number} latitude
 */
ListingCreationRequestDTO.prototype['latitude'] = undefined;

/**
 * @member {Number} longitude
 */
ListingCreationRequestDTO.prototype['longitude'] = undefined;






export default ListingCreationRequestDTO;

