/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListingResponseDTO from './ListingResponseDTO';

/**
 * The ListingListResponseDTO model module.
 * @module model/ListingListResponseDTO
 * @version 1.0
 */
class ListingListResponseDTO {
    /**
     * Constructs a new <code>ListingListResponseDTO</code>.
     * @alias module:model/ListingListResponseDTO
     */
    constructor() { 
        
        ListingListResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListingListResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListingListResponseDTO} obj Optional instance to populate.
     * @return {module:model/ListingListResponseDTO} The populated <code>ListingListResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListingListResponseDTO();

            if (data.hasOwnProperty('listings')) {
                obj['listings'] = ApiClient.convertToType(data['listings'], [ListingResponseDTO]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListingListResponseDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListingListResponseDTO</code>.
     */
    static validateJSON(data) {
        if (data['listings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['listings'])) {
                throw new Error("Expected the field `listings` to be an array in the JSON data but got " + data['listings']);
            }
            // validate the optional field `listings` (array)
            for (const item of data['listings']) {
                ListingResponseDTO.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ListingResponseDTO>} listings
 */
ListingListResponseDTO.prototype['listings'] = undefined;






export default ListingListResponseDTO;

