/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The SearchHistoryResponseDTO model module.
 * @module model/SearchHistoryResponseDTO
 * @version 1.0
 */
class SearchHistoryResponseDTO {
    /**
     * Constructs a new <code>SearchHistoryResponseDTO</code>.
     * @alias module:model/SearchHistoryResponseDTO
     */
    constructor() { 
        
        SearchHistoryResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchHistoryResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchHistoryResponseDTO} obj Optional instance to populate.
     * @return {module:model/SearchHistoryResponseDTO} The populated <code>SearchHistoryResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchHistoryResponseDTO();

            if (data.hasOwnProperty('searchQuery')) {
                obj['searchQuery'] = ApiClient.convertToType(data['searchQuery'], 'String');
            }
            if (data.hasOwnProperty('searchedAt')) {
                obj['searchedAt'] = ApiClient.convertToType(data['searchedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchHistoryResponseDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchHistoryResponseDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['searchQuery'] && !(typeof data['searchQuery'] === 'string' || data['searchQuery'] instanceof String)) {
            throw new Error("Expected the field `searchQuery` to be a primitive type in the JSON string but got " + data['searchQuery']);
        }

        return true;
    }


}



/**
 * @member {String} searchQuery
 */
SearchHistoryResponseDTO.prototype['searchQuery'] = undefined;

/**
 * @member {Date} searchedAt
 */
SearchHistoryResponseDTO.prototype['searchedAt'] = undefined;






export default SearchHistoryResponseDTO;

