spring:
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:h2:file:./data/marketplaceDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true