spring:
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:h2:file:./data/marketplaceDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.web.multipart: DEBUG