/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthenticationRequestDTO from '../model/AuthenticationRequestDTO';
import TokenResponseDTO from '../model/TokenResponseDTO';
import UserRequestDTO from '../model/UserRequestDTO';

/**
* AuthenticationController service.
* @module api/AuthenticationControllerApi
* @version 1.0
*/
export default class AuthenticationControllerApi {

    /**
    * Constructs a new AuthenticationControllerApi. 
    * @alias module:api/AuthenticationControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the authenticate operation.
     * @callback module:api/AuthenticationControllerApi~authenticateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/AuthenticationRequestDTO} authenticationRequestDTO 
     * @param {module:api/AuthenticationControllerApi~authenticateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponseDTO}
     */
    authenticate(authenticationRequestDTO, callback) {
      let postBody = authenticationRequestDTO;
      // verify the required parameter 'authenticationRequestDTO' is set
      if (authenticationRequestDTO === undefined || authenticationRequestDTO === null) {
        throw new Error("Missing the required parameter 'authenticationRequestDTO' when calling authenticate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = TokenResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/auth/authenticate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the register operation.
     * @callback module:api/AuthenticationControllerApi~registerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/UserRequestDTO} userRequestDTO 
     * @param {module:api/AuthenticationControllerApi~registerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponseDTO}
     */
    register(userRequestDTO, callback) {
      let postBody = userRequestDTO;
      // verify the required parameter 'userRequestDTO' is set
      if (userRequestDTO === undefined || userRequestDTO === null) {
        throw new Error("Missing the required parameter 'userRequestDTO' when calling register");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = TokenResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/auth/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the registerAdmin operation.
     * @callback module:api/AuthenticationControllerApi~registerAdminCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/UserRequestDTO} userRequestDTO 
     * @param {module:api/AuthenticationControllerApi~registerAdminCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponseDTO}
     */
    registerAdmin(userRequestDTO, callback) {
      let postBody = userRequestDTO;
      // verify the required parameter 'userRequestDTO' is set
      if (userRequestDTO === undefined || userRequestDTO === null) {
        throw new Error("Missing the required parameter 'userRequestDTO' when calling registerAdmin");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = TokenResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/auth/register/admin', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
