/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ChatResponseDTO from '../model/ChatResponseDTO';
import MessageRequestDTO from '../model/MessageRequestDTO';
import MessageResponsetDTO from '../model/MessageResponsetDTO';

/**
* ChatController service.
* @module api/ChatControllerApi
* @version 1.0
*/
export default class ChatControllerApi {

    /**
    * Constructs a new ChatControllerApi. 
    * @alias module:api/ChatControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {String} chatId 
     * @param {module:model/MessageRequestDTO} messageRequestDTO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MessageResponsetDTO} and HTTP response
     */
    addMessageToChatWithHttpInfo(chatId, messageRequestDTO) {
      let postBody = messageRequestDTO;
      // verify the required parameter 'chatId' is set
      if (chatId === undefined || chatId === null) {
        throw new Error("Missing the required parameter 'chatId' when calling addMessageToChat");
      }
      // verify the required parameter 'messageRequestDTO' is set
      if (messageRequestDTO === undefined || messageRequestDTO === null) {
        throw new Error("Missing the required parameter 'messageRequestDTO' when calling addMessageToChat");
      }

      let pathParams = {
        'chatId': chatId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = MessageResponsetDTO;
      return this.apiClient.callApi(
        '/api/v1/chat/{chatId}/message', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} chatId 
     * @param {module:model/MessageRequestDTO} messageRequestDTO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MessageResponsetDTO}
     */
    addMessageToChat(chatId, messageRequestDTO) {
      return this.addMessageToChatWithHttpInfo(chatId, messageRequestDTO)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} listingId 
     * @param {module:model/MessageRequestDTO} messageRequestDTO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ChatResponseDTO} and HTTP response
     */
    createChatFromBuyerWithHttpInfo(listingId, messageRequestDTO) {
      let postBody = messageRequestDTO;
      // verify the required parameter 'listingId' is set
      if (listingId === undefined || listingId === null) {
        throw new Error("Missing the required parameter 'listingId' when calling createChatFromBuyer");
      }
      // verify the required parameter 'messageRequestDTO' is set
      if (messageRequestDTO === undefined || messageRequestDTO === null) {
        throw new Error("Missing the required parameter 'messageRequestDTO' when calling createChatFromBuyer");
      }

      let pathParams = {
        'listingId': listingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ChatResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/listing/{listingId}/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} listingId 
     * @param {module:model/MessageRequestDTO} messageRequestDTO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ChatResponseDTO}
     */
    createChatFromBuyer(listingId, messageRequestDTO) {
      return this.createChatFromBuyerWithHttpInfo(listingId, messageRequestDTO)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} listingId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ChatResponseDTO>} and HTTP response
     */
    getAllChatsForListingWithHttpInfo(listingId) {
      let postBody = null;
      // verify the required parameter 'listingId' is set
      if (listingId === undefined || listingId === null) {
        throw new Error("Missing the required parameter 'listingId' when calling getAllChatsForListing");
      }

      let pathParams = {
        'listingId': listingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [ChatResponseDTO];
      return this.apiClient.callApi(
        '/api/v1/listing/{listingId}/chats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} listingId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ChatResponseDTO>}
     */
    getAllChatsForListing(listingId) {
      return this.getAllChatsForListingWithHttpInfo(listingId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ChatResponseDTO>} and HTTP response
     */
    getAllChatsForUserWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [ChatResponseDTO];
      return this.apiClient.callApi(
        '/api/v1/user/my-chats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ChatResponseDTO>}
     */
    getAllChatsForUser() {
      return this.getAllChatsForUserWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} listingId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ChatResponseDTO} and HTTP response
     */
    getChatWithHttpInfo(listingId) {
      let postBody = null;
      // verify the required parameter 'listingId' is set
      if (listingId === undefined || listingId === null) {
        throw new Error("Missing the required parameter 'listingId' when calling getChat");
      }

      let pathParams = {
        'listingId': listingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ChatResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/listing/{listingId}/chat', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} listingId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ChatResponseDTO}
     */
    getChat(listingId) {
      return this.getChatWithHttpInfo(listingId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
