/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SearchHistoryListResponseDTO from '../model/SearchHistoryListResponseDTO';
import SearchHistoryRequestDTO from '../model/SearchHistoryRequestDTO';
import SearchHistoryResponseDTO from '../model/SearchHistoryResponseDTO';

/**
* SearchHistoryController service.
* @module api/SearchHistoryControllerApi
* @version 1.0
*/
export default class SearchHistoryControllerApi {

    /**
    * Constructs a new SearchHistoryControllerApi. 
    * @alias module:api/SearchHistoryControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the add operation.
     * @callback module:api/SearchHistoryControllerApi~addCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchHistoryResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/SearchHistoryRequestDTO} searchHistoryRequestDTO 
     * @param {module:api/SearchHistoryControllerApi~addCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchHistoryResponseDTO}
     */
    add(searchHistoryRequestDTO, callback) {
      let postBody = searchHistoryRequestDTO;
      // verify the required parameter 'searchHistoryRequestDTO' is set
      if (searchHistoryRequestDTO === undefined || searchHistoryRequestDTO === null) {
        throw new Error("Missing the required parameter 'searchHistoryRequestDTO' when calling add");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = SearchHistoryResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/search-history/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the findByUserId operation.
     * @callback module:api/SearchHistoryControllerApi~findByUserIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchHistoryListResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/SearchHistoryControllerApi~findByUserIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchHistoryListResponseDTO}
     */
    findByUserId(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = SearchHistoryListResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/search-history/get-my-history', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
