/**
 * OpenAPI Documentation - find.no
 * OpenApi documentation for find.no
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BookmarkRequestDTO from '../model/BookmarkRequestDTO';
import BookmarkResponseDTO from '../model/BookmarkResponseDTO';

/**
* BookmarkController service.
* @module api/BookmarkControllerApi
* @version 1.0
*/
export default class BookmarkControllerApi {

    /**
    * Constructs a new BookmarkControllerApi. 
    * @alias module:api/BookmarkControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createBookmark operation.
     * @callback module:api/BookmarkControllerApi~createBookmarkCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookmarkResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a bookmark for a listing
     * @param {module:model/BookmarkRequestDTO} bookmarkRequestDTO 
     * @param {module:api/BookmarkControllerApi~createBookmarkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookmarkResponseDTO}
     */
    createBookmark(bookmarkRequestDTO, callback) {
      let postBody = bookmarkRequestDTO;
      // verify the required parameter 'bookmarkRequestDTO' is set
      if (bookmarkRequestDTO === undefined || bookmarkRequestDTO === null) {
        throw new Error("Missing the required parameter 'bookmarkRequestDTO' when calling createBookmark");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = BookmarkResponseDTO;
      return this.apiClient.callApi(
        '/api/v1/bookmarks/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteBookmark operation.
     * @callback module:api/BookmarkControllerApi~deleteBookmarkCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a bookmark
     * @param {String} bookmarkId 
     * @param {module:api/BookmarkControllerApi~deleteBookmarkCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteBookmark(bookmarkId, callback) {
      let postBody = null;
      // verify the required parameter 'bookmarkId' is set
      if (bookmarkId === undefined || bookmarkId === null) {
        throw new Error("Missing the required parameter 'bookmarkId' when calling deleteBookmark");
      }

      let pathParams = {
        'bookmarkId': bookmarkId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/bookmarks/{bookmarkId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserBookmarks operation.
     * @callback module:api/BookmarkControllerApi~getUserBookmarksCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BookmarkResponseDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Getting all bookmarks for a user
     * @param {module:api/BookmarkControllerApi~getUserBookmarksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BookmarkResponseDTO>}
     */
    getUserBookmarks(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [BookmarkResponseDTO];
      return this.apiClient.callApi(
        '/api/v1/bookmarks/my-bookmarks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
